insert into departamento (id_departamento, nombre_departamento) values(1,'GUATEMALA');
insert into departamento (id_departamento, nombre_departamento) values(2,'EL PROGRESO');
insert into departamento (id_departamento, nombre_departamento) values(3,'SACATEPEQUEZ');
insert into departamento (id_departamento, nombre_departamento) values(4,'CHIMALTENANGO');
insert into departamento (id_departamento, nombre_departamento) values(5,'ESCUINTLA');
insert into departamento (id_departamento, nombre_departamento) values(6,'SANTA ROSA');
insert into departamento (id_departamento, nombre_departamento) values(7,'SOLOLA');
insert into departamento (id_departamento, nombre_departamento) values(8,'TOTONICAPAN');
insert into departamento (id_departamento, nombre_departamento) values(9,'QUETZALTENANGO');
insert into departamento (id_departamento, nombre_departamento) values(10,'SUCHITEPEQUEZ');
insert into departamento (id_departamento, nombre_departamento) values(11,'RETALHULEU');
insert into departamento (id_departamento, nombre_departamento) values(12,'SAN MARCOS');
insert into departamento (id_departamento, nombre_departamento) values(13,'HUEHUETENANGO');
insert into departamento (id_departamento, nombre_departamento) values(14,'QUICHE');
insert into departamento (id_departamento, nombre_departamento) values(15,'BAJA VERAPAZ');
insert into departamento (id_departamento, nombre_departamento) values(16,'ALTA VERAPAZ');
insert into departamento (id_departamento, nombre_departamento) values(17,'PETEN');
insert into departamento (id_departamento, nombre_departamento) values(18,'IZABAL');
insert into departamento (id_departamento, nombre_departamento) values(19,'ZACAPA');
insert into departamento (id_departamento, nombre_departamento) values(20,'CHIQUIMULA');
insert into departamento (id_departamento, nombre_departamento) values(21,'JALAPA');
insert into departamento (id_departamento, nombre_departamento) values(22,'JUTIAPA');

insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Guatemala',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Santa Catarina Pinula',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San José Pinula',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San José el Golfo',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Palencia',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Chinautla',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'San Pedro Ayampuc',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Mixco',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Pedro Sacatepéquez',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'San Juan Sacatepéquez',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'San Raimundo',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Chuarrancho',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Fraijanes',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Amatitlán',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Villa Nueva',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Villa Canales',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Petapa',1);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Guastatoya',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Morazán',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Agustín Acasaguastlán',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Cristóbal Acasaguastlán',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'El Jícaro',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Sansare',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Sanarate',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Antonio La Paz',2);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Antigua Guatemala',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Jocotenango',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Pastores',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Sumpango',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Santo Domingo Xenacoj',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Santiago Sacatepéquez',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'San Bartolomé Milpas Altas',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Lucas Sacatepéquez',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Santa Lucía Milpas Altas',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Magdalena Milpas Altas',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Santa María de Jesús',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Ciudad Vieja',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'San Miguel Dueñas',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Alotenango',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'San Antonio Aguas Calientes',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Santa Catarina Barahona',3);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Chimaltenango',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San José Poaquil',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Martín Jilotepeque',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Comalapa',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Santa Apolonia',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Tecpán Guatemala',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Patzún',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Pochuta',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Patzicía',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Santa Cruz Balanyá',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Acatenango',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Yepocapa',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'San Andrés Itzapa',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Parramos',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Zaragoza',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'El Tejar',4);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Escuintla',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Santa Lucía Cotzumalguapa',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'La Democracia',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Siquinalá',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Masagua',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Tiquisate',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'La Gomera',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Guanagazapa',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San José',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Iztapa',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Palín',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'San Vicente Pacaya',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Nueva Concepción',5);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Cuilapa',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Barberena',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Santa Rosa de Lima',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Casillas',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'San Rafael las Flores',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Oratorio',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'San Juan Tecuaco',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Chiquimulilla',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Taxisco',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Santa María Ixhuatán',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Guazacapán',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Santa Cruz Naranjo',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Pueblo Nuevo Viñas',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Nueva Santa Rosa',6);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Sololá',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San José Chacayá',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Santa María Visitación',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Santa Lucía Utatlán',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Nahualá',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Santa Catarina Ixtahuacán',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Santa Clara La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Concepción',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Andrés Semetabaj',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Panajachel',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Santa Catarina Palopó',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'San Antonio Palopó',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'San Lucas Toliman',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Santa Cruz La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'San Pablo La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'San Marcos La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'San Juan La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'San Pedro La Laguna',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'Santiago Atitlán',7);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Totonicapán',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San Cristobal Totonicapán',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Francisco El Alto',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Andrés Xecul',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Momostenango',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Santa María Chiquimula',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Santa Lucía La Reforma',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Bartolo',8);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Quetzaltenango',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Salcajá',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Olintepeque',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Carlos Sija',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Sibilia',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Cabricán',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Cajolá',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Miguel Siguilá',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Ostuncalco',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'San Mateo',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Concepción Chiquirichapa',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'San Martín Sacatepéquez',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Almolonga',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Cantel',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Huitán',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Zunil',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Colomba',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'San Francisco La Unión',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'El Palmar',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(20,'Coatepeque',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(21,'Génova',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(22,'Flores Costa Cuca',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(23,'La Esperanza',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(24,'Palestina de los Altos',9);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Mazatenango',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Cuyotenango',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Francisco Zapotitlán',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Bernardino',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'San José El Idolo',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Santo Domingo Suchitepéquez',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'San Lorenzo',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Samayac',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Pablo Jocopilas',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'San Antonio Suchitepéquez',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'San Miguel Panán',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'San Gabriel',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Chicacao',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Patulul',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Santa Bárbara',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'San Juan Bautista',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Santo Tomás La Unión',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'Zunilito',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'Pueblo Nuevo',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(20,'Rio Bravo',10);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Retalhuleu',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San Sebastián',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Santa Cruz Muluá',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Martín Zapotitlán',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'San Felipe',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'San Andrés Villa Seca',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Champerico',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Nuevo San Carlos',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'El Asintal',11);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'San Marcos',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San Pedro Sacatepéquez',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Antonio Sacatepéquez',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Comitancillo',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'San Miguel Ixtahuacán',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Concepción Tutuapa',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Tacaná',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Sibinal',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Tajumulco',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Tejutla',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'San Rafael Pié de La Cuesta',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Nuevo Progreso',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'El Tumbador',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'El Rodeo',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Malacatán',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Catarina',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Ayutla',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'Ocós',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'San Pablo',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(20,'El Quetzal',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(21,'La Reforma',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(22,'Pajapita',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(23,'Ixchiguán',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(24,'San José Ojetenam',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(25,'San Cristóbal Cucho',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(26,'Sipacapa',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(27,'Esquipulas Palo Gordo',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(28,'Rio Blanco',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(29,'San Lorenzo',12);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Huehuetenango',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Chiantla',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Malacatancito',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Cuilco',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Nentón',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'San Pedro Necta',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Jacaltenango',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Soloma',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Ixtahuacán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Santa Bárbara',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'La Libertad',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'La Democracia',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'San Miguel Acatán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'San Rafael La Independencia',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Todos Santos Cuchumatán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'San Juan Atitán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Santa Eulalia',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'San Mateo Ixtatán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'Colotenango',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(20,'San Sebastián Huehuetenango',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(21,'Tectitán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(22,'Concepción Huista',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(23,'San Juan Ixcoy',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(24,'San Antonio Huista',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(25,'San Sebastián Coatán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(26,'Barillas',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(27,'Aguacatán',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(28,'San Rafael Petzal',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(29,'San Gaspar Ixchil',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(30,'Santiago Chimaltenango',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(31,'Santa Ana Huista',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(32,'Unión Cantinil',13);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Santa Cruz del Quiché',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Chiché',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Chinique',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Zacualpa',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Chajul',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Chichicastenango',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Patzité',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Antonio Ilotenango',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Pedro Jocopilas',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Cunén',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'San Juan Cotzal',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Joyabaj',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Nebaj',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'San Andrés Sajcabajá',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Uspantán',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Sacapulas',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'San Bartolomé Jocotenango',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(18,'Canillá',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(19,'Chicamán',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(20,'Ixcán',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(21,'Pachalum',14);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Salamá',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San Miguel Chicaj',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Rabinal',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Cubulco',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Granados',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'El Chol',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'San Jerónimo',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Purulhá',15);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Cobán',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Santa Cruz Verapaz',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Cristóbal Verapaz',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Tactic',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Tamahú',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Tucurú',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Panzós',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Senahú',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Pedro Carchá',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'San Juan Chamelco',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Lanquín',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Cahabón',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Chisec',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Chahal',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Fray Bartolomé de Las Casas',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'Santa Catalina la Tinta',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Raxruhá',16);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Flores',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San José',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Benito',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Andrés',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'La Libertad',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'San Francisco',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Santa Ana',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Dolores',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'San Luis',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Sayaxché',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Melchor de Mencos',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Poptún',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Las cruces',17);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Puerto Barrios',18);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Livingston',18);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'El Estor',18);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Morales',18);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Los Amates',18);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Zacapa',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'Estanzuela',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Río Hondo',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Gualán',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Teculután',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Usumatlán',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Cabañas',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'San Diego',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'La Unión',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Huité',19);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Chiquimula',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San José La Arada',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Juan Erminta',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Jocotán',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Camotán',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Olopa',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Esquipulas',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Concepción Las Minas',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'Quetzaltepeque',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'San Jacinto',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Ipala',20);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Jalapa',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'San Pedro Pinula',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'San Luis Jilotepeque',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'San Manuel Chaparrón',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'San Carlos Alzatate',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Monjas',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Mataquescuintla',21);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(1,'Jutiapa',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(2,'El Progreso',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(3,'Santa Catarina Mita',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(4,'Agua Blanca',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(5,'Asunción Mita',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(6,'Yupiltepeque',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(7,'Atescatempa',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(8,'Jerez',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(9,'El Adelanto',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(10,'Zapotitlán',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(11,'Comapa',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(12,'Jalpatagua',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(13,'Conguaco',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(14,'Moyuta',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(15,'Pasaco',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(16,'San José Acatempa',22);
insert into municipio (id_municipio, nombre_municipio, id_departamento) values(17,'Quezada',22);

